### ISSUE TITLE
Add edge neutral model

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#106]
This would be useful for understanding passive signals.

**Comment by shaunhaskey** [comment]
@lstagner This would be very useful for @bgrierson21 and I!

**Comment by lstagner** [comment]
This has been partially implemented in #134 . In that PR we added the ability to input a cold neutral profile and simulate the passive FIDA/NPA.

**Comment by lstagner** [comment]
This probably isn't going to happen. We have the ability to input edge neutral density and that will suffice for now.
