### ISSUE TITLE
Need Visualization Tools

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#108]
We need a way visualize the inputs and outputs. In python preferably.

**Comment by shaunhaskey** [comment]
@lstagner I have quite a few python scripts for looking at the neutral densities, or the spectra. What sort of features are you thinking? Sorry haven't gotten around to extracting my python setup scripts from OMFIT.

**Comment by lstagner** [comment]
Here is my feature wish list

* Python (or not IDL)
* GUI interface
* Command line interface
* Plots inputs: geometry/profiles/...
* Plots outputs: spectra/npa/weights...

A few years ago I had done some work on a [GUI for FIDASIM](https://github.com/lstagner/FIDASIM-GUI). It may be time to resurrect that project
