### ISSUE TITLE
Error in relative stark intensity calculation

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#122]
I was trying to find a reference for the [relative stark intensities](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L81) we use and I noticed the following from a recent thesis.
***
![image](https://cloud.githubusercontent.com/assets/4305891/21960357/1c9f050c-da9d-11e6-8c44-b1dc078b757a.png)
***
The angular distributions described above (Eq. 3.5) are different from the ones [used in FIDASIM](https://github.com/D3DEnergetic/FIDASIM/blob/release-0.3//fidasim.f90#L2595) and in Ben Geigers thesis. 
***
![image](https://cloud.githubusercontent.com/assets/4305891/21960352/fae32326-da9c-11e6-9715-b4c9ad8a5006.png)
***
Which does include a factor of 1/2 but he describes it as a instrumental factor that is specific to AUG. This may explain why he didn't notice it.

I have complied a short literary search. Unfortunately each paper contradicts the other. 

## Doesn't have factor of 1/2
* Ben Geigers Thesis 
* Mandl, W., et al. "Beam emission spectroscopy as a comprehensive plasma diagnostic tool." Plasma physics and controlled fusion 35.10 (1993): 1373. 
* Jakubowska, Katarzyna, et al. "Motional Stark effect diagnostic on TEXTOR." Review of scientific instruments 75.10 (2004): 3475-3477.

## Has factor of 1/2
* Development of the B-Stark motional Stark effect diagnostic for measurements of the internal magnetic field in the DIII-D tokamak - N. Pablant
* Gu, M. F., et al. "Atomic models for the motional Stark effect diagnostic." Journal of Physics B: Atomic, Molecular and Optical Physics 41.9 (2008): 095701.

After thinking about it a bit I think the right answer is that the factor of two is needed. If you integrate the two pdfs you will find that you need the factor of two so that they have the same normalization factor.

I am unsure of the effect fixing would have since it depends on the angle between the LOS and the induced Electric field but I suspect that it would broaden the spectrum slightly. 

Does anybody have an opinion on which one is right?

**Comment by lstagner** [comment]
I did a FIDASIM run with the factor of two and it most drastically affects the NBI spectra

![image](https://cloud.githubusercontent.com/assets/4305891/21962042/545c9ad6-dacf-11e6-9843-2351ca1eb018.png)


The Halo and FIDA are also somewhat effected mostly in the wings of the spectra.

![image](https://cloud.githubusercontent.com/assets/4305891/21962055/e2a22a4a-dacf-11e6-8d8f-b8aefeb4df25.png)

**Comment by bgrierson21** [comment]
Luke, can you make the beam emission plot on a linear scale? These look like big changes, and we can validate which one is correct using experimental data.

**Comment by lstagner** [comment]
Sure thing. 
![image](https://cloud.githubusercontent.com/assets/4305891/21965821/745f466a-db1c-11e6-9317-94d41b8b7c11.png)

This was shot 159243 at 791 ms using chord 1/33.
The files are at 
No Factor: `/p/fida/lstagner/ORBIT_TOM/159243L01/791_spectra.h5`
With Factor: `/p/fida/lstagner/ORBIT_TOM/159243L01/791_spectra_sav.h5`

**Comment by bgrierson21** [comment]
Luke, thanks.  I think that for higher field or angle w.r.t. beam it will be much more obvious because the Stark components will be more spread out.  We can compare this to a DIII-D to verify which one is correct.

**Comment by shaunhaskey** [comment]
@lstagner @bgrierson21 Luke if you can point me to the two executables on portal I can run a simulation for the main ion system chords which will make comparisons with experiment easy.

**Comment by lstagner** [comment]
@shaunhaskey It's pretty trivial to fix yourself. All you have to do is take [this line](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L5766) and turn it into
```fortran
where (stark_sigma .eq. 1)
    intensity = intensity * sigma_pi*0.5
endwhere
````

But just in case I made the two executables `/u/lstagner/FIDASIM/fidasim_stark`(fixed) and `/u/lstagner/FIDASIM/fidasim`(normal)

**Comment by lstagner** [comment]
I found a paper that uses both definitions simultaneously. In the paper by Delabie[1] he doesn't use the factor of 2 in the formal definition but in the following figure he multiplies by a factor of 2 for seemingly no reason

![image](https://cloud.githubusercontent.com/assets/4305891/22007435/789b6b58-dc27-11e6-91e6-28b12c613b10.png)

[1] Delabie, E., et al. "Consistency of atomic data for the interpretation of beam emission spectra." Plasma Physics and Controlled Fusion 52.12 (2010): 125008.

**Comment by shaunhaskey** [comment]
@lstagner Should have the runs done, and able to check them tomorrow.

**Comment by shaunhaskey** [comment]
Comparison between 'normal' and factor of 2 for the 16 main ion chords:

![screenshot_685](https://cloud.githubusercontent.com/assets/3589208/22035697/cbb8c320-dca5-11e6-992e-34a0d84debae.png)

Comparison between experiment and normal (note instrumental response is not included):
![screenshot_686](https://cloud.githubusercontent.com/assets/3589208/22035743/f63c029c-dca5-11e6-9128-31b007c3ab45.png)


Comparison between experiment and factor of 1/2 (note instrumental response is not included):
![screenshot_687](https://cloud.githubusercontent.com/assets/3589208/22035747/f9ab9a64-dca5-11e6-9dfe-0efcdc5d9dec.png)

I need to apply the instrumental response to the FIDASIM data (not coded up yet) but at the moment it is sort of looking like the factor of 1/2 has better agreement.

**Comment by shaunhaskey** [comment]
Note in that last comment I had to update one of the figures because I made a mistake (so if you are only looking at it in your emails it might be the old version of the message....)

**Comment by lstagner** [comment]
Thanks @shaunhaskey . Does the main ion system use any mirrors? Because the difference in the reflection coefficients of the sigma and pi lines has the the same effect as the factor of 1/2.  Could the the factor of 1/2 be a mirror property?

**Comment by lstagner** [comment]
Ok its looking like the factor of 1/2 is needed. I found a derivation in the appendix of a paper[1] and that led me to find it in Jackson(The ultimate authority) Section 9.9 Table 9.1

@shaunhaskey could you still apply the instrumental response. I would like to confirm my conclusion and also see how well FIDASIM does. If it doesn't perfectly fit the spectra steps should be taken to fix it. 

[1] Howard, John, et al. "Time-resolved two-dimensional plasma spectroscopy using coherence-imaging techniques." Plasma physics and controlled fusion 45.7 (2003): 1143.

**Comment by shaunhaskey** [comment]
@lstagner There is a mirror - it is a metal coating on the back of a glass slide type of mirror so I don't think it will care that much about polarisation, that is more for reflection by dielectrics isn't it? I need to read up more on this because I never thought about this much. I'll also get in contact with the MSE people to ask them about the mirror and this 1/2 business. It will take me a day or two to include the instrumental response, but I'll get it done - needs to happen sooner or later. Funny you should reference that paper, it is from on of my thesis advisors.

**Comment by victorbs** [comment]
There are a couple of things to consider with mirrors: 1. Diattenuation: this would cause a difference in the percent of light transmitted based on the polarization angle of the light; 2. Retardance: this would cause a rotation in the polarization angle of the light. Since you are only measuring the magnitude of the light, the only effect that would likely cause problems is diattenuation. From my experience working on MSE, mirrors complicate the measurement considerable, but I believe our problems arise predominantly from retardance caused by the mirror. I'm not sure the best way to characterize the effects of diattenuation in your system.

As far as the line ratios, I think the factor of 1/2 comes from the fact that there are 2 pi lines and 1 sigma line and the net polarization of the light is zero. Also, experimentally, it is difficult to isolate a single transition line within the 'sigma line' or the 'pi lines'.

**Comment by lstagner** [comment]
Posting this here for the public record

>Ok I think I know whats going on. Everyone is right. For a single transition |nlm> -> |n'l'm'> The factor of 1/2 is needed so that the normalization factors of the pi and sigma angular distributions are the same. (Also Jackson says its needed so...). However, the sigma lines are actually two(4 for sigma0) different transitions due to the sign of the magnetic quantum number e.g. for the sigma1 the transitions are |0,1,1> -> |0,1,0> and |0,1,-1> -> |0,1,0>. So if the intensity of a sigma line is given by
>
>I_s = (1+cos(th)^2)*(A_{s- }+ A_{s-})*P/2
>
>where P is the level population A_{s+/-} is the transition probability.
>Since A_{s} = A_{s}  you get
>
>I_s = (1+cos(th)^2)*2*A_{s+}*P/2 = (1+cos(th)^2)*A_{s+}*P
>
>The factors of 2 cancel. 

So everything is fine and what we have in the code is correct. So I am closing this issue. 

@shaunhaskey You should continue investigating since it looks like the main-ion system should use a non-unity sigma_pi ratio in its [diagnostics settings.](http://d3denergetic.github.io/FIDASIM/page/02_physics/05_spectra.html#spectroscopic-geometry)
