### ISSUE TITLE
Documentation is incorrectly recursive

### ISSUE THREAD

**Issue by cbcoutinho** [D3DEnergetic/FIDASIM#124]
I was just perusing your project and noticed a documentation error. Your release doc sends me to the development branch of FIDASIM at the front page, but then on the master branch the link is still there. Clicking it brings me to a 404 error because it tries to go into the master branch again

I'm trying to get FORD to work for a small project I'm working on as well - how do you guys structure your docs? Is it using gh-pages?

The reason I ask, is because I'm a little confused as to how you put all the docs into `docs/html/index.html`, whereas github gives the option of only `docs/index.html`. I also want to through all of my documentation into a directory along with an html subdirectory, but I'm not sure how github can access it then.

**Comment by cbcoutinho** [comment]
Oops, just noticed the magic is handled by Travis. Thanks for the great project, it's a great source of inspiration

**Comment by lstagner** [comment]
Yes, I am aware of that bug. Its not a huge issue so I let it be.

We use Travis to automatically build and deploy our documentation website (see the deploy.sh file). I used this guide https://gist.github.com/domenic/ec8b0fc8ab45f39403dd to set it up.

**Comment by cbcoutinho** [comment]
Sounds good, it didn't seem like the kind of thing to keep you up at night.

Thanks for the tip, I got my travis ci service up and running based on your method and the guide. Works great!
