### ISSUE TITLE
What happened to python prefida in master?

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#126]
@lstagner What happened to python prefida in master? It looks like it disappeared!

**Comment by lstagner** [comment]
its still there. Its in `lib/python/fidasim`

If you set
```
export PYTHONPATH=$FIDASIM_DIR/lib/python:$PYTHONPATH
```

you should be able to do 
```python
>>> import fidasim
>>> fidasim.prefida(inputs, grid, nbi, plasma, fields, dist, spec=spec, npa=npa)
```

**Comment by shaunhaskey** [comment]
oops, didn't realise everything had been consolidated into a couple of files
