### ISSUE TITLE
FIDASIM 2.0 Wishlist

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#131]
Yesterday I released what I think will be the last release of the 1.0 series. So in the spirit of looking forward I have compiled a list of features I think should be in the 2.0 release. If anyone has any additional feature requests this would be the place to mention it. 

- [x] 3D Equilibrium
- [x] Input Edge Neutrals part of Issue #106 
- [ ] FILD calculation (given an input distribution at the aperture)
- [x] Better visualization scripts in Python
- [ ] Ability to call FIDASIM routines from Python (WIP on ls/pywrap branch)
- [x] MPI based parallelism (Maybe v3.0)  
- [x] More Python preprocessing routines
- [ ] Testing Framework
- [ ] Better beam grid and passive grid creation. Let user manually set grid parameters or allow FIDASIM to do it.

**Comment by sjjamsa** [comment]
+1 On the 3D Equilibrium :-)

I looked a bit at the source code with this in mind. It seems that the changes to the main source code would be limited to perihipery of getfields() and getplasma().
If non-axisymmetric distribution function is used, then also get_ep_denf() needs updating.

Am I missing any other significant alteration needs? Any deep assumptions of axisymmetry?

Best regards,
 - Simppa -

**Comment by lstagner** [comment]
The subroutines to read in the equilibrium/distribution would also need to be changed. Also any change will also have to be somewhat backwards compatible just to make things easier. No need to force someone to use a 3D equilibrium when they don't have to.  Something like assume a 2D equilibrium if the equilibrium file does not have a phi variable or the phi variable has length 1.

**Comment by lstagner** [comment]
Update on v2.0.0 progress

On the development version of FIDASIM (master branch) we now have nominial 3D functionality, MPI parallelism, the ability to calculate passive signals from cold edge neutrals, and more complete python preprocessing routines. Currently we are working on the visualization scripts (#152) and further improvements in the passive calculations (presently you have to make the beam grid very large to cover the lines of sight which is not ideal).

@sjjamsa, ,You seemed interested in the 3D equilibrium. Do you have a good test case we could use to benchmark the code?
