### ISSUE TITLE
iris MPI issue

### ISSUE THREAD

**Issue by djlin1** [D3DEnergetic/FIDASIM#150]
I received and error while running FIDASIM D3D's iris cluster.

> write fida weights:    12:56:39 --- elapsed: 0:16:20 
Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(907).......: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x2b4979629ec0, count=307500000, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(764).: 
MPIR_Allreduce_intra(268): 
MPIR_Bcast_impl(1452)....: 
MPIR_Bcast(1476).........: 
MPIR_Bcast_intra(1287)...: 
MPIR_Bcast_binomial(250).: message sizes do not match across processes in the collective routine: Received -32766 but expected -1834967296
Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(907).......: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x2aaf8981cec0, count=307500000, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(764).: 
MPIR_Allreduce_intra(268): 
MPIR_Bcast_impl(1452)....: 
MPIR_Bcast(1476).........: 
MPIR_Bcast_intra(1287)...: 
MPIR_Bcast_binomial(250).: message sizes do not match across processes in the collective routine: Received -32766 but expected -1834967296
Fatal error in MPI_Allreduce: Other MPI error, error stack:
MPI_Allreduce(907).......: MPI_Allreduce(sbuf=MPI_IN_PLACE, rbuf=0x2aaedfbabec0, count=307500000, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD) failed
MPIR_Allreduce_impl(764).: 
MPIR_Allreduce_intra(268): 
MPIR_Bcast_impl(1452)....: 
MPIR_Bcast(1476).........: 
MPIR_Bcast_intra(1287)...: 
MPIR_Bcast_binomial(250).: message sizes do not match across processes in the collective routine: Received -32766 but expected -1834967296

As a result I was not able to get the FIDA weights file but I was still able to get the other outputs like the spectra file.

**Comment by lstagner** [comment]
Could you put all the input files for the run in the scratch area so we can debug.

@sfiligoi do you know what the problem is?

**Comment by djlin1** [comment]
I reduced the number of energy weights (ne_wght=75 to ne_wght=50) and was able to successfully execute FIDASIM.
I used the command `submit_fidasim -m 20G 9000_inputs.dat` to submit the run.
The input files for the failed run are placed in `/cscratch/lindan/fidasim_issue` for now.

**Comment by lstagner** [comment]
Im just going to chalk this up to exceeding the memory limit set by the scheduler.
