### ISSUE TITLE
First using of FIDASIM

### ISSUE THREAD

**Issue by nightkeo** [D3DEnergetic/FIDASIM#156]
I tried to run test (run_tests, 'D: \ FIDASIM-1.3.2') code and got an error in read_geqdsk.pro. There is no function g = readg (filename).

And is there a test example on python?

**Comment by nightkeo** [comment]
Tried;

idl 6 Ubuntu 16.04

idl 8.5 Windows 8.1

**Comment by alvin-garcia** [comment]
Hello,

The location of readg is `/FIDASIM/deps/efit`

You need to declare the path of this file in your bash or csh script. For example:

```
export PATH=$FIDASIM_DIR/deps/efit:$PATH
``` 
or
```
setenv PATH {$FIDASIM_DIR}/deps/efit:{$PATH}
```

Yes, there are python scripts in `/FIDASIM/test/` that can be executed from the command line.

**Comment by nightkeo** [comment]
Thank you!

Now it works)
