### ISSUE TITLE
plot_outputs problem

### ISSUE THREAD

**Issue by nightkeo** [D3DEnergetic/FIDASIM#160]
Dear FIDASIM team, 
It is not very clear how to use the program plot_outputs. What is the definition of the -d directory argument and -p path? And what terminal command is needed to view the output test data? My output test data is located in FIDASIM directory in "test" folder.

My command "python plot_outputs -d /home/madsc/soft/FIDASIM_new -r test -p /home/madsc/soft/FIDASIM_new/test -n".
Terminal output:
"
p
/home/madsc/soft/FIDASIM_new/test
filedir
/home/madsc/soft/FIDASIM_new/test
False

Traceback (most recent call last):
  File "plot_outputs", line 433, in <module>
    main()
  File "plot_outputs", line 395, in main
    raise IOError('File path doesn\'t exist')
IOError: File path doesn't exist
"

**Comment by alvin-garcia** [comment]
Hello @nightkeo ,

I am glad to see you are using our visualization scripts. I encourage you to continue using them. Our next FIDASIM release will include new features that I have incorporated.

It looks like you are trying to plot npa data for a test case.

`-d` will plot data from the spectra, npa and neutrons hdf5 files located in `/home/madsc/soft/FIDASIM_new` with runid `test` (which you have indicated with `-r`). If any of the three files is **not** present, the code will crash. Only use this command if you want to plot **everything** inside your folder.

`-p` might be all you need. `-p /home/madsc/soft/FIDASIM_new/test_npa -n -ln 1` will plot the active npa data for channel 1. Note that you must indicate the type of data you need (`-n` for active or `-pn` for passive) and what channel you want to view (`-ln 1 3` for channels 1 and 3; `-rn 1 3` for channels 1, 2, 3; `-an` for channels 1, 2, ..., N). Also note, this command can handle a list of files, e.g. `-p ~/test_npa ~/test2_npa ~/test3_npa -n -ln 1`

```plot_outputs -h``` will show you more commands. What I have mentioned applies for spectral data with analogous commands.

I hope this helps!

-Alvin
