### ISSUE TITLE
Problems with FIDAsim on HL-2A

### ISSUE THREAD

**Issue by kerui-swip** [D3DEnergetic/FIDASIM#163]
Dear FIDAsim, 

Greatings from BES group of HL-2A! 

I have installed the FIDAsim on the cluster and run the test program sucessfully. However, the FIDAsim did not response this morning. I typed ./fidasim as usual, nothing happened. No FIDASIM startup info, no error. Do you have any suggestion for this situation? Should I uninstall it and re-install? 

Thanks, 
Rui

**Comment by lstagner** [comment]
`./fidasim` will only work if you are in the fidasim directory or you have extended the fidasim directory to your `PATH` environment variable in your `.bashrc` (or equivalent file if you are not using a bash shell (you can do `echo $SHELL` to figure out if you are using bash) ). 

Generally you should setup your `.bashrc` file to include the following (changing the paths accordingly)
```
export FIDASIM_DIR=/path/to/fidasim/install/directory
export FC=gfortran #use 'ifort' for Intel Fortran compiler
export CC=gcc      #use 'icc' for Intel C compiler
export CXX=g++     #use 'icpc' for Intel C++ compiler

#For using helper routines
export PATH=$FIDASIM_DIR/deps/hdf5/bin:$FIDASIM_DIR/lib/scripts:$PATH
export IDL_PATH="+$FIDASIM_DIR:$IDL_PATH:<IDL_DEFAULT>"
export PYTHONPATH=$FIDASIM_DIR/lib/python:$PYTHONPATH

ulimit -s unlimited #Omit this if you like segfaults
```

**Comment by kerui-swip** [comment]
Hi Luke, 
I was in the fidasim directory. it worked for the test case, but does not response any case all of a sudden now. Like this: 
`[kerui@mgmt ~]$ cd /home/kerui/FIDASIM-1.3.2/
`
`
[kerui@mgmt FIDASIM-1.3.2]$ ./fidasim
`
`
[kerui@mgmt FIDASIM-1.3.2]$
`
Nothing happened. No startup info, no error info. Setup of the `PATH` cannot fix this problem. Do you have any suggestions? 

Thanks, 
Rui

**Comment by lstagner** [comment]
That's interesting, the fidasim executable must be in the directory or else it would of thrown an `bash: ./fidasim: No such file or directory` error. Have you tried recompiling?

**Comment by kerui-swip** [comment]
Well,  nothing changed after recompiling. 
```
[kerui@mgmt FIDASIM-1.3.2]$ make
make[1]: Entering directory `/home/kerui/FIDASIM-1.3.2/deps'
make[1]: `hdf5' is up to date.
make[1]: Leaving directory `/home/kerui/FIDASIM-1.3.2/deps'
make[1]: Entering directory `/home/kerui/FIDASIM-1.3.2/src'
make[1]: `/home/kerui/FIDASIM-1.3.2/fidasim' is up to date.
make[1]: Leaving directory `/home/kerui/FIDASIM-1.3.2/src'
make[1]: Entering directory `/home/kerui/FIDASIM-1.3.2/tables'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/kerui/FIDASIM-1.3.2/tables'
[kerui@mgmt FIDASIM-1.3.2]$
```

**Comment by lstagner** [comment]
First run `make clean` then `make` If that doesn't work then show me the output of `ldd fidasim` this will tell me if the executable is being correctly linked to the system libraries

**Comment by kerui-swip** [comment]
Wow! I run `make clean` before `make`. It works now! Thank you so much!

**Comment by lstagner** [comment]
yes. `make clean` removes all the previously compiled files. I guess something changed in your environment that caused the dynamic linking to fail. But anyway I am glad everything is now working.
