### ISSUE TITLE
rho is sqrt(normalized toroidal flux) or toroidal flux?

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#165]
@lstagner The documentation for this function says that if psi=True it will return the normalized poloidal flux otherwise the normalized toroidal flux:

https://github.com/D3DEnergetic/FIDASIM/blob/653224a26bac0ac5e5bbf0e872a9c2e2782a162f/lib/python/fidasim/utils.py#L677

It wasn't clear to me if it actually returns the square root of those quantities. There are some sqrts in the functions, but I'm not sure exactly how the calculations work. To add to the confusion, the variable name rho is used (eg def rho_rz) which typically means sqrt(norm tor flux) - at least on DIII-D. Please clarify.

**Comment by lstagner** [comment]
Normalized poloidal flux, psi, is defined as sqrt((psi - psi_axis)/psi_wall)
```python
fluxgrid = np.array([psirz_itp(rr,zz) for (rr,zz) in zip(r_pts,z_pts)]).reshape(dims)
fluxgrid = np.sqrt((fluxgrid - g["ssimag"])/g["ssibry"])
```
Rho is also normalized in a similar way but it is not obvious by looking at the code. The `rho` returned by `fluxmap` is just `rho = np.linspace(0.0, np.sqrt(flux_b/bcentr), 101)` with `flux_b` being the toroidal flux enclosed by the LCFS. To normalize this `rho` we divide its max  value but since it already has the `sqrt` it has the same normalization as the poloidal flux.

**Comment by bgrierson21** [comment]
@lstagner that is incorrect.  There are three common definitions.
Normalized psi "psi_n" is just the normalized poloidal flux (psi - psi_0)/(psi_bry-psi_0), no square root.
If you square root "psi_n" then you get "rho_poloidal", or "rho_p", which is less common.
The other common one is "rho" or "normalized rho toroidal", which is sqrt(normalized toroidal flux), where the normalization is again (X-X_0)/(X_bry-X_0).

**Comment by lstagner** [comment]
OK. In that case what "normalized" poloidal and toroidal flux means in the code is "rho_p" and "rho", respectively. At some point we should change the code to make things clear.

**Comment by shaunhaskey** [comment]
@lstagner you originally said that the normalization is wrt the poloidal flux at the wall. I didn't mention it earlier because I thought it was a typo, but I think I'm seeing an issue related to this...

psi_n is supposed to be 1 at the last closed flux surface so using Brian's notation, psi_n=(psi - psi_0)/(psi_bry-psi_0) where psi_0 is poloidal flux at the magnetic axis and psi_bry is the poloidal flux at the last closed flux surface (not the same as the wall in diverted plasmas).

Please could you confirm whether psi_n=1 means the last closed flux surface or the wall at the moment?

**Comment by lstagner** [comment]
The  `psiwall` variable in the `read_geqdsk` function is the `ssibry` variable in the geqdsk file which the EFIT documentation states is the poloidal flux at the plasma boundary. I take that to mean the poloidal flux at the LCFS.

**Comment by bgrierson21** [comment]
Correct.  The variables `ssimag` and `ssibry` are the magnetic axis and boundary (separatrix) poloidal flux.

**Comment by shaunhaskey** [comment]
Hmmm, then something weird is going on. Here is a  simple test case (on iris):

```
import numpy as np
import fidasim
import matplotlib.pyplot as plt
geqdsk_fname="/fusion/projects/xpsi/grierson/efit/164988/Z07/FILES_129/g164988.03525"

rmax=234.
rmin=200
nr=350
zmax=100.
zmin=-100.
rgrid_nz=300
grid = fidasim.utils.rz_grid(rmin, rmax, nr, zmin, zmax, rgrid_nz)
equil, flux, btipsign = fidasim.utils.read_geqdsk(geqdsk_fname, grid, psi=True)
r = grid['r']
z = grid['z']
z_0_ind = np.argmin(np.abs(z))
fig, ax = plt.subplots()
ax.plot(r, flux[:,z_0_ind])
ax.axvline(228.9)
fig.canvas.draw();fig.show()
```
Produces the plot below. RMIDOUT (LCFS @Z=0) is 228.9cm according to efit viewer for this efit but "flux" [sqrt(psi_n)] returned by read_geqdsk is not one at that value, and it never goes above 1.

![Selection_058](https://user-images.githubusercontent.com/3589208/58756113-77bfb200-84a6-11e9-9b71-570190d35333.png)

**Comment by lstagner** [comment]
Hmm... try plotting the LCFS from the gfile and see if it crosses the midplane (z=0) at r=228.9. Also, you should evaluate psi (unnormalized) at the LCFS and see if it agrees with the `ssibry` variable.

**Comment by shaunhaskey** [comment]
I got those numbers from EFITviewer (also in the screenshot), so they are probably correct.

I'm pretty sure the bug is here (denominator is missing a -g['ssimag']:

https://github.com/D3DEnergetic/FIDASIM/blob/653224a26bac0ac5e5bbf0e872a9c2e2782a162f/lib/python/fidasim/utils.py#L716

Should be:
```
fluxgrid = np.sqrt((fluxgrid - g["ssimag"])/(g["ssibry"]-g["ssimag"]))
```

If this is the problem I can submit a pull request with the changes as well as a few other changes I made

**Comment by shaunhaskey** [comment]
Same plot from earlier but with that fix:

![Selection_059](https://user-images.githubusercontent.com/3589208/58765345-01af5f80-8527-11e9-8595-06e1980bcd68.png)

Seems to do the trick

**Comment by lstagner** [comment]
Well thats not good....If you make a PR with a fix could you also change the idl version as well. Fortunately, this shouldn't affect `rho` (`sqrt(normalized toroidal flux)`) which is more commonly used but I will have to check my ASDEX cases which do use `rho_p`.

**Comment by lstagner** [comment]
OK I'm going to just go ahead and fix this. No need to open a PR

**Comment by lstagner** [comment]
I have fixed the issue and published a new release. I have also updated the routines on the master branch to use the correct terminology. The release and development installs on iris and portal have been updated.

**Comment by lstagner** [comment]
Dodged a bullet. When you extract an equilibrium from a TRANSP run the `ssimag` variable is set to zero so wrong normalization didn't affect my ASDEX cases.

**Comment by bgrierson21** [comment]
@lstagner but if you give FIDASIM a gEQDSK from EFIT or some other code `ssimag` will not be zero.  So in principle anyone who used psi *could* have a run in error.

**Comment by lstagner** [comment]
I meant to say *I* dodged a bullet because my only case that used `rho_p` happened to be fine. Just thought I'd share that this shouldn't of been a problem if you used an geqdsk extracted from TRANSP which is a common workflow
