### ISSUE TITLE
COCOS convention and Ip & Bt orientation

### ISSUE THREAD

**Issue by kiselevnightkeo** [D3DEnergetic/FIDASIM#168]
Dear FIDASIM team,

What cocos convention is used in code?
We find it difficult to understand how a poloidal and toroidal field sign is given? Conter or clockwise?

Thank you!

**Comment by kiselevnightkeo** [comment]
And questions:

In which units the particle flux is measured in the runid_npa.h5 file?
And what flux (active or passive) is calculated by the method of weight functions in NPA?

**Comment by alvin-garcia** [comment]
In our code, positive magnetic field points in the counterclockwise (ccw) direction. Pitch is measured with respect to the magnetic field.

All FIDASIM outputs have tags in their hdf5 structure. For example, tag names for the npa flux are description, units and data. Printing units would show neutrals/(s*dE).

**Comment by kiselevnightkeo** [comment]
Thank you!

And what flux (active or passive) is calculated by the method of weight functions in NPA?

What is the meaning of dE? 1 keV? 1 eV?

**Comment by lstagner** [comment]
The NPA weight function method only calculates active signals. If you want passive NPA you will have to use the Monte Carlo method (`calc_pnpa = 1` in the inputs.dat file). The units for all calculated quantities are stored in the HDF5 as attributes. You can access them using the idl routine `read_hdf5.pro` which will automatically read in all the attributes. For `dE` the units are in keV.  For future reference all the energy units are in `keV`
