### ISSUE TITLE
Bad passive FIDA signals when passive NPA calculation is turned on

### ISSUE THREAD

**Issue by BlehMaks** [D3DEnergetic/FIDASIM#172]
[Passive_FIDA_issue.zip](https://github.com/D3DEnergetic/FIDASIM/files/3432676/Passive_FIDA_issue.zip)
Dear FIDASIM team,

I found out that calculation of passive NPA (pnpa) signals affects somehow on calculation of passive FIDA (pfida) signals (or may be on writing outputs to spectra.h5). If I set switch calc_pnpa:0, all works well and output data in spectra.h5 for passive FIDA look well. But if I set switch calc_pnpa:1, signals from chords 10-16 become equal to zero. Also, if I set switch calc_pnpa:2, signals from chords 11-16 are equal to zero and signal from chord 10 is two orders of magnitude smaller than normal signal but nonzero. So, some dependencies are present.
On the other hand, calculations of FIDA and NPA signals are separated in FIDASIM code, so pNPA should not affect on pFIDA.
May I ask you please to check this point? In my opinion this calculations should not affect each other and for the moment it is not true.
In attached archive you may find three sets of pictures: 1) calc_pnpa:0, 2) calc_pnpa:1, 3) calc_pnpa:2, also you may find configuration files in attachment. 

Thank you in advance!

**Comment by alvin-garcia** [comment]
Dear @BlehMaks,

Thank you for opening an issue on GitHub. This is our preferred method of communication.

My new [passive branch](https://github.com/D3DEnergetic/FIDASIM/tree/ag/passive3) has resolved your issues.

We will wait a bit to see if any new related issues arise before merging my new branch into the development (master) version.

Thank you.

-Alvin

**Comment by BlehMaks** [comment]
Dear @alvin-garcia,

Thank you very much for your response and help!
For the moment all works good, if something goes wrong, I will let you know.

Best regards,
Maksim

**Comment by alvin-garcia** [comment]
Dear @BlehMaks,

Sounds good. I have made some more changes and they are part of the the master branch.

Thank you.

Best,

Alvin

**Comment by BlehMaks** [comment]
Dear @alvin-garcia,

Regular simulations of TCV systems go well now after fixing passive neutral grid bug.
But, recently, I have got passive neutral grid errors again. 

We were trying to find out the best position for mounting of horizontal FIDA on TCV. To do this I created an array of lines of sight (chords) and each of them certainly intersects the neutral beam (they were calculated so). And for some of them I got passive neutral grid errors (those which are in attached files). 

There are some chords, that intersect the first and the last point of beam, I may expect, that it is incorrect case for FIDASIM run. But other chords producing this error, intersect beam on its length and I was surprised to get errors. 

Could you please check, if it is a part of FIDASIM bug related to passive neutrals grid?

Thank you in advance!
Best regards,
Maksim
[Another_passive_grid_errors_from_TCV.zip](https://github.com/D3DEnergetic/FIDASIM/files/3577964/Another_passive_grid_errors_from_TCV.zip)

**Comment by alvin-garcia** [comment]
@BlehMaks,

Thank you for reaching out with your issue. Please post screenshots of your output file, input geometry, etc. We can assist you quicker if you post more information.

**Comment by BlehMaks** [comment]
Dear @alvin-garcia,

Sorry for this delay, you may find a picture of my geometry input, this is horizontal FIDA system, so it is in the equatorial plane. Unfortunately, I am not able to make screenshots of other input files from my work PC, but I will try from home if it is still needed.

Thank you in advance!
Best regards,
Maksim

**Comment by alvin-garcia** [comment]
@BlehMaks,

This issue has been fixed.

**Comment by BlehMaks** [comment]
@alvin-garcia,
Thank you very much! We have already updated FIDASIM after merging.
