### ISSUE TITLE
NPA & pNPA "missed detector" errors

### ISSUE THREAD

**Issue by BlehMaks** [D3DEnergetic/FIDASIM#176]
Dear FIDASIM team,

Now we have only one problem left with FIDASIM simulations on TCV.
This problem appears for every NPA lines of sight, that we tried. When NPA and pNPA Monte-Carlo simulations are running, there are errors of such type as
"NPA_F: Missed Detector            3"
"PNPA_F: Missed Detector            3".
Number of missed particles is relatively small comparing to number of particles that "hit" detector (~100/50000 respectively).
Could you please help to understand what can cause these errors and how we can solve this problem in general?
Please find input files in attachment.
Thank you in advance!

Best regards,
Maksim
[npa_errors.zip](https://github.com/D3DEnergetic/FIDASIM/files/3670527/npa_errors.zip)

**Comment by BlehMaks** [comment]
Also, please find attached input files which exactly describe experimental setup for this particular shot 62124.
The first message contains NPA lines of sight which are also possible since TCV has remote control of NPA lines of sight.
Thank you in advance for your help and comments!
Best regards,
Maksim
[npa_err_exp_setup.zip](https://github.com/D3DEnergetic/FIDASIM/files/3671933/npa_err_exp_setup.zip)

**Comment by lstagner** [comment]
This is a common problem which I haven't figured out yet. It is most likely due to floating point errors. Since the number of missed particles is small compared to the number that hit, it is safe to ignore these errors.
