### ISSUE TITLE
Python preprocessing errors in tests

### ISSUE THREAD

**Issue by BlehMaks** [D3DEnergetic/FIDASIM#177]
Dear FIDASIM team,

I am trying to test my FIDASIM installed on virtual machine. I installed FIDASIM itself and all dependencies for python 3.7.5 (unfortunately I am not able to use python 3.8 as default at the moment). I am trying to run test case and I am getting errors connetced with wrong dimensions of arrays of plasma profiles. See screen shot attached.  
Could you please tell me how to fix this?
Thank you in advance!

Best regards,
Maksim
![Снимок экрана от 2019-11-07 11-53-56](https://user-images.githubusercontent.com/52274532/68374198-7a10f100-0155-11ea-9924-5e54558acd3b.png)

**Comment by lstagner** [comment]
@alvin-garcia this falls under your purview.

**Comment by BlehMaks** [comment]
Thank you for fixing this problem, now test case run well. I will try python scripts with real parameters and I will let you know if something goes wrong.

Best regards,
Maksim

**Comment by alvin-garcia** [comment]
@BlehMaks,

Sure, happy to help.

**Comment by alvin-garcia** [comment]
Also, you may encounter errors with data types when preparing your inputs and running prefida. If this happens, use python optional argument `dtype` when defining variables to match what our python code accepts.

**Comment by BlehMaks** [comment]
@alvin-garcia,
Thank you very much for your advise!
I am happy to make you code better.
