### ISSUE TITLE
Inconsistency in passive t-FIDA spatial profile between two methods

### ISSUE THREAD

**Issue by deyongl** [D3DEnergetic/FIDASIM#180]
It seems there are some inconsistency in passive-FIDA simulations between the current master version (with passive interpolation grids) and Bill's old approach (i.e., replacing the beam-neutral density in every  beam grid with the background neutral density interpolated from TRANSP output).  In principle,  these two approaches should get the same results. The two plots below shows the comparison of passive t-FIDA and passive v-FIDA signal profile using two approaches. 
(a) Passive t_FIDA profile (the lines with the prefix "passive_" are from Bill's old approach, and the other lines are from the passive signals from the current FIDASIM  master version). There is a relatively large discrepancy between two methods.
![image](https://user-images.githubusercontent.com/12468380/70945905-0511c080-200b-11ea-9dad-dffee08c54ae.png)
(b) Passive v_FIDA profile (the lines with the prefix "passive_" are from Bill's old approach, and the other lines are from the passive signals from the current FIDASIM  master version). Two methods here get reasonable agreement.
![image](https://user-images.githubusercontent.com/12468380/70945509-3938b180-200a-11ea-8728-d68115885fd1.png)

**Comment by lstagner** [comment]
@deyongl did you make the beam grid large enough to cover the entire sightline?

**Comment by deyongl** [comment]
@lstagner I thought about this when I firstly saw the discrepancy. The beam grids do cover the all the edge region near the entrance side of t-FIDA, but not on the exit-machine side. I would expect the passive t-FIDA signals from the old approach may be equal or less than that from the new interpolation approach. But the top plot shows the passive t-FIDA signals from the old approach is actually larger than the new interpolation approach in the region with Rmaj<110cm.

**Comment by lstagner** [comment]
@deyongl 

Try running your code on this commit 4fb642337a80f988a21b117cb6b94ec076f433bb. Its the commit before alvins 3D changes. The passive method it uses is the one where the edge neutrals are mapped onto the beam grid but it is done internally. It's the one I implemented and it should be correct.

**Comment by lstagner** [comment]
We have identified two possible issues. One is that the chords can see through walls and we didn't have enough phi values. We can fix the first one by providing the wall as an input or at the very least the rmin of the center stack. The second bit we can fix by just increasing the nphi values in the passive grid. Since there are no plasma parameters stored on the passive grid there isn't any memory issues.

**Comment by lstagner** [comment]
@deyongl I can't remember did this get resolved?
