### ISSUE TITLE
nubeam_geometry bug + spectra question

### ISSUE THREAD

**Issue by BlehMaks** [D3DEnergetic/FIDASIM#193]
Dear FIDASIM team,

1) I suspect that routine nubeam_geometry in python preprocessing has a bug in lines 1200-1203
    There should probably be:
    1200    phi_a = phi_s + nubeam["NLJCCW"] * nubeam["NLCO"] * **(beta_a)**
    1202    src = np.array([rs * np.cos(phi_s **+ beta_s**), rs * np.sin(phi_s **+ beta_s**),zs])
    1203    aper_src = np.array([ra * np.cos(phi_a), ra * np.sin(phi_a),za])

    or may be it would be better to make construction of phi_s the same as of phi_a and leave strings 
    1202-1203 as they was

    1200    phi_a = phi_s + nubeam["NLJCCW"] * nubeam["NLCO"] * **(beta_a)**
                phi_s = phi_s + nubeam["NLJCCW"] * nubeam["NLCO"] * **(beta_s)**
    1202    src = np.array([rs * np.cos(phi_s), rs * np.sin(phi_s),zs])
    1203    aper_src = np.array([ra * np.cos(phi_a), ra * np.sin(phi_a),za])
2) I have a question regarding to spectral calculations. I noticed, that all spectra have units 
    "Ph/(s * nm * sr * m^2)". Does it mean that these spectra are local? If so, for what spatial point are 
    they given?
    I thought, that FIDA synthetic diagnostic in FIDASIM should provide line-integrated spectra (as the 
    real FIDA diagnostic), is not it?

Thank you in advance for your response!

Best regards,
Maksim

**Comment by alvin-garcia** [comment]
@BlehMaks,

Thanks for finding the bug and suggesting a solution.

Your thought is correct, FIDASIM outputs the line-integrated spectra. If this were not the case, the units would have an extra factor of "m" in the denominator.
