### ISSUE TITLE
A patch proposed to fix 2.0.0-pre build for mingw-w64.

### ISSUE THREAD

**Issue by zhubr** [D3DEnergetic/FIDASIM#195]
Please see attached a patch against 2.0.0-pre to fix a mingw build.
The patch is so tiny and trivial I'd suppose it is worth considering.
Thanks.
[mingw.patch.zip](https://github.com/D3DEnergetic/FIDASIM/files/4874595/mingw.patch.zip)

**Comment by lstagner** [comment]
I tried applying the patch but it failed. Could you open a PR?

**Comment by zhubr** [comment]
> I tried applying the patch but it failed. Could you open a PR?

Sorry I'm not very used to git in general, so I can't do exactly that. But, attached here is a 'git diff' output against current 2.0 branch checkout, and as I've heard, 'git apply' should accept such formatting perfectly fine. Alternatively, if it still does not, I think you could also apply this patch to your local copy with just plain old 'patch -p1' and it will basically do the same thing.

[mingw-2.0.0.patch.zip](https://github.com/D3DEnergetic/FIDASIM/files/5043008/mingw-2.0.0.patch.zip)

**Comment by lstagner** [comment]
Thanks for the new patch. I have implemented the changes on the master branch.
