### ISSUE TITLE
Dependencies description for 2.0.0-pre version

### ISSUE THREAD

**Issue by zhubr** [D3DEnergetic/FIDASIM#196]
Hello,
It would be nice to have specifically documented the employed python modules (that is, numpy, scipy, skimage, matplotlib, h5py) in the "Dependencies" section, ideally with some reference compatible version numbers, or if possible, compatible version ranges. That would save quite a lot of burden in preparing a compatible environment.
Also, the reference to Anacond Python in "Dependencies" section currently points to a "404 error".
And while we are at it, the command example in "Run a test case" section should better be "python run_tests.py ..." because automagic interpreter selection might not work well (depending on specific environment).
Thanks.

**Comment by lstagner** [comment]
Thanks for the suggestion. We are currently working on better support for python (PR #203)
