### ISSUE TITLE
Test failure (in 2.0.0-pre): numpy int32 vs int64 types

### ISSUE THREAD

**Issue by zhubr** [D3DEnergetic/FIDASIM#197]
Hello,
I'm getting this (in run_tests.py):

ERROR: "mask" has the wrong type of <class 'numpy.int32'>. Expected [<class 'num
py.int64'>]
ERROR: Invalid plasma parameters. Exiting...

Probably it has to do with various versions of libraries and python modules, anyway I could not find a solution yet. Numpy is 1.19.0 here currently. Not sure which other versions are relevant.
Thanks.

**Comment by zhubr** [comment]
Changing np.int64 to np.int32 in nrnznphi_int assignment in preprocessing.py made tests complete normally.
Still not sure if such change is correct and why it was necessary here.
Thanks.

**Comment by lstagner** [comment]
Thanks for reporting this. I changed the mask type and run_tests.py works for me.
