### ISSUE TITLE
gfortran 4.8 (opensuse 13.2) fails to compile utilities.f90 (in 2.0.0-pre)

### ISSUE THREAD

**Issue by zhubr** [D3DEnergetic/FIDASIM#200]
Hello,
I'm observing the following error using gfortran 4.8.3 (as per opensuse 13.2) and unmodified FIDASIM-2.0.0-pre.zip.
I suspect it is because 4.8 is too old, however the Getting Started page states > 4.6 is ok. 
So should gfortran 4.8 be fine or rather not?
<pre>
gfortran -Ofast -g -fbacktrace -cpp -D_VERSION=\"2.0.0-pre\" -fopenmp -D_OMP -c utilities.f90
utilities.f90:665.27:

    call c_f_pointer(c_loc(w), w_ptr, [nw])
                           1
Error: Assumed-shape array 'w' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
</pre>

**Comment by lstagner** [comment]
I would of thought it would be fine but we haven't tested on gfortran 4.6 in a while. I will update the docs to specify that gfortran5 is required now.
