### ISSUE TITLE
Calculate cold signal along full LOS

### ISSUE THREAD

**Issue by lamorton** [D3DEnergetic/FIDASIM#213]
Presently, it looks like the cold signal is only calculated on the portion of the spectrometer LOS that lies inside the beam grid.

**Comment by lstagner** [comment]
Hmm. Your right thats an oversight on our part. @alvin-garcia can you take care of this? All you need to do is change the beam grid functions to use the interpolation/passive grid instead.

**Comment by alvin-garcia** [comment]
@lstagner,

Sure, looks easy.
