### ISSUE TITLE
Errors in HDF5 in FIDASIM-2.0.0

### ISSUE THREAD

**Issue by struggleSD** [D3DEnergetic/FIDASIM#217]
Dear FIDASIM team,

I'm using the FIDASIM-2.0.0, but every time after running prefida through .py, when I try to submit the FIDASIM job, something wrong happened to HFD5 like:

 "HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 0:
  #000: H5F.c line 522 in H5Fcreate(): unable to create file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1003 in H5F_open(): unable to open file:"
 
HDF5(1.8.16) can't creat, read and write.

I'm sure I’ve given the  folders permissions, andI have tried different versions of HDF5, I can't figure out what's wrong.
Could you please tell me how to fix this?

Regards

**Comment by lstagner** [comment]
Can you run `ls -l` in the directory where the input files are? The folder may have the right permissions but file permissions may be different.

**Comment by struggleSD** [comment]
> Can you run `ls -l` in the directory where the input files are? The folder may have the right permissions but file permissions may be different.

Thanks for your reply.
I have checked that. I even gave the folder and the input files the highest authority “chmod 777”, but it didn't work

**Comment by lstagner** [comment]
OK can you try opening the HDF5 file with python. If python cant read it then that indicates that the file is corrupted and something went wrong in the file writing process.

**Comment by lstagner** [comment]
Also could you attach the files needed to reproduce the error.

**Comment by struggleSD** [comment]
> OK can you try opening the HDF5 file with python. If python cant read it then that indicates that the file is corrupted and something went wrong in the file writing process.

I tested it. Python can read and write HDF5 files, FIDASIM can also run successfully on login nodes , but when I submit FIDASIM job to a cluster. It happens. And I'm sure that I load the same version:HDF5(1.8.16).


[FIDASIM_log.txt](https://github.com/D3DEnergetic/FIDASIM/files/5450873/FIDASIM_log.txt)

**Comment by lstagner** [comment]
It could be that the cluster you are using disallows writing files in certain directories when using compute nodes. This is done to prevent overloading the distributed file system. Your cluster should have a scratch area where programs are free to write files. You should try changing the result directory to point towards that area.

**Comment by lstagner** [comment]
Are you still having this issue?

**Comment by struggleSD** [comment]
> Are you still having this issue?

Sorry for the slow reply,recently the server have been shut down  for maintenance, before that I tried once, It seems like it doesn't work. Once the server start， I'll try again.
