### ISSUE TITLE
FIDASIM will not run through if one of the beam currents is zero

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#219]
It is useful to simulate only a full energy beam, i.e current_fractions = 1,0,0 (interested in comparing FIDASIM apparent velocities that occur due to cross section distortions with analytic approaches). This causes the current master branch of FIDASIM to fail when it gets to the DCX calculation: 
![image](https://user-images.githubusercontent.com/3589208/101849700-19e53f00-3b0d-11eb-8497-44b63a509431.png)

Presumably there is a divide by zero somewhere when calculating the number of DCX to launch - I looked briefly but couldn't see where this would be happening. @lstagner let me know if the fix/issue is obvious, otherwise I'll keep digging around. A work around is to use trace amounts of half, and third energy currents.

**Comment by lstagner** [comment]
Yeah I cant find the problem quickly. I'll have to look into more thoroughly.

**Comment by lstagner** [comment]
This was fixed in the latest commit. The fix was as simple as skipping over the nbi density calculation if the current fraction was zero

**Comment by shaunhaskey** [comment]
@lstagner Thanks! Do you understand why it couldn't handle 0 current (just wondering if there is a deeper bug)?

**Comment by lstagner** [comment]
My guess is that nans were introduced in colrad when it tried to solve for some coefficients
```fortran
call linsolve(eigvec,states,coef) !coeffs determined from states at t=0
```

**Comment by lstagner** [comment]
Ahh that wasn't it. The problem was when calculating the neutral cx rate by averaging over the stored neutral trajectories. The problem was that the trajectories had zero weight so it introduced a divide by zero. Skipping the zero current fractions side stepped the issue because no trajectories were stored. I just pushed the proper fix.

```diff
diff --git a/src/fidasim.f90 b/src/fidasim.f90
index 6ec1dd6..a74e482 100644
--- a/src/fidasim.f90
+++ b/src/fidasim.f90
@@ -8384,18 +8384,21 @@ subroutine neutral_cx_rate(denn, res, v_ion, rates)

     integer :: i
     real(Float64), dimension(nlevs) :: rates_i
-    real(Float64) :: vn(3)
+    real(Float64) :: vn(3), totw

     !! Average CX rate over Reservoir
     rates = 0.d0
     if(res%n.eq.0) return

+    totw = sum(res%R%w)
+    if(totw.eq.0.d0) return
+
     do i=1, min(res%n,res%k)
         vn = res%R(i)%v
         call bb_cx_rates(denn,vn,v_ion,rates_i)
         rates = rates + res%R(i)%w*rates_i
     enddo
-    rates = rates/sum(res%R%w)
+    rates = rates/totw

 end subroutine neutral_cx_rate
```

**Comment by shaunhaskey** [comment]
Great, thanks for digging for the underlying problem!
