### ISSUE TITLE
Output rest wavelength and species mass

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#220]
@lstagner Suggest outputting the rest wavelength and mass of the ion specie(s) that were used to calculate the spectra in the spectra.h5 file.

Calculating the apparent temperature and velocity of the thermal spectrum from FIDASIM requires a rest wavelength and species mass. These values have to match the values that FIDASIM is using to high precision (because c is big) otherwise the velocity corrections won't be right. I currently get the mass and rest wavelength that FIDASIM uses from the source code but this is error prone and might change.

I can implement this, just wanted to see if there were any suggestions about the best place/way to store this data.

**Comment by lstagner** [comment]
This is a good idea. The best thing to do is to just output into the spectra.h5 file as you suggested.

What you need to write to the file is the module variables (`thermal_mass(1:n_thermal)` and `thermal_lambda0(1:n_thermal)`)

**Comment by shaunhaskey** [comment]
@lstagner Ok, want me to add it to my existing pull request branch or start a new one?

Also output beam_mass, beam_lambda0 and fast_ion_mass, fast_ion_lambda0? Or just stick with the thermal ones because that is where getting it right is most important?

**Comment by lstagner** [comment]
you can add it to your existing PR and just do the thermal ones. No reason to clutter the file unnecessarily.

**Comment by shaunhaskey** [comment]
Added to #218
