### ISSUE TITLE
Funny-looking double assignment

### ISSUE THREAD

**Issue by lamorton** [D3DEnergetic/FIDASIM#221]
It looks like the next line was intended to replace this one, but both are still sitting there.  Not 100% sure though b/c I'm still trying to grok this part of the code.
https://github.com/D3DEnergetic/FIDASIM/blob/6860f94b24abe3b3c80d6872c9e282c84b89c3d3/src/fidasim.f90#L11911

**Comment by lstagner** [comment]
The first line sets the direction of the nbi injection and the second line normalizes vnbi_f so it has the right magnitude.
