### ISSUE TITLE
Refactoring for testing purposes

### ISSUE THREAD

**Issue by lamorton** [D3DEnergetic/FIDASIM#222]
I'd like to be able to run some tests that exercise various FIDASIM subroutines.  I found out that because the main program and the libfida module are in the same file, Fortran won't allow me to include libfida in any other programs -- I get an error because now gfortran sees two main programs.  It would be relatively easy to put libfida in a separate file to enable this.  (Or, do you know of any trick that would allow me to use libfida without having to split up the file?)

**Comment by lstagner** [comment]
I feel like it should be possible to compile a new program but I cant think of it off the top of my head. I think you just need to include the .mod/.o files when you compile your program. That being said, we should probably split libfida and fidasim (the main program) into separate files. Create a libfida.f90 and fidasim.f90

**Comment by lamorton** [comment]
I found out there's a hack to use `libfida` in a different main program [https://stackoverflow.com/a/65652159](using GNU objcopy to mark the `_main` symbol  from `fidasim.o` as a weak reference). 

> That being said, we should probably split libfida and fidasim (the main program) into separate files. Create a libfida.f90 and fidasim.f90

Great, I think that's a better way to go. I can submit a PR once I iron out the last bugs.

**Comment by lstagner** [comment]
No need for you to do anything I made a new PR for the change
