### ISSUE TITLE
The wrong type "float" of “nx,ny,nz”

### ISSUE THREAD

**Issue by struggleSD** [D3DEnergetic/FIDASIM#224]
Dear FIDASIM team,

I'm using the FIDASIM-2.0.0, when using the prefida for inputs through python, I set the beam grid  as defult
 "basic_bgrid = fs.utils.beam_grid(nbi,250.0)", but the error happened:
""nx"has the weong type of <type float>"
I don't know why this happen, but in the python script I changed the type:
"basic_bgrid['nx'] = int(basic_bgrid['nx'])
basic_bgrid['ny'] = int(basic_bgrid['ny'])
basic_bgrid['nz'] = int(basic_bgrid['nz'])"
This worked, but spectra and weight function changed, the intensity of FIDA, BES, and halo became stronger except for bremsstrahlung. Is this a bug or my setting si wrong?

Thanks in advance for your response!
![1](https://user-images.githubusercontent.com/55744730/104670752-64169d00-5717-11eb-9174-c5261572a41d.png)
![image](https://user-images.githubusercontent.com/55744730/104670896-ab9d2900-5717-11eb-85d8-20db8f4440cd.png)

**Comment by lstagner** [comment]
Well that shouldn't happen. Could you send me the inputs.dat files(these files contain the beam grid settings) for each run you showed above.
