### ISSUE TITLE
What modules am I missing on iris? - FIDASIM 2.0

### ISSUE THREAD

**Issue by camicollins** [D3DEnergetic/FIDASIM#233]
Working on making inputs and it looks like the module is missing some basic paths -  what all do I need to load?  
module purge
module load defaults
module load fidasim/v2.0
idl
IDL> gfile='/fusion/projects/results/transp/collinscs/180620C51/g180620.03000' 
IDL> grid=rz_grid(100,240,140,-100,100,200) ;; rz_grid(rmin,rmax,nr,zmin,zmax,nz)
IDL> fields=read_geqdsk(gfile,grid,rho=rho,btipsign=btipsign)
  >>> in efit_read_mds_time: minmax of efittime
% Attempt to call undefined procedure: 'MINMAX'.
% Execution halted at: EFIT_READ_MDS_TIME  458 /fusion/projects/codes/fidasim/v2.0/deps/efit/efit_read.pro
%                      EFIT_READ_MDS     721 /fusion/projects/codes/fidasim/v2.0/deps/efit/efit_read.pro
%                      EFIT_READ         827 /fusion/projects/codes/fidasim/v2.0/deps/efit/efit_read.pro
%                      READG             932 /fusion/projects/codes/fidasim/v2.0/deps/efit/readg.pro
%                      READ_GEQDSK       155 /fusion/projects/codes/fidasim/v2.0/lib/idl/read_geqdsk.pro
%                      $MAIN$

**Comment by alvin-garcia** [comment]
Hi @camicollins,

I recently had the exact same issue and thought FIDASIM was missing a dependency somewhere. Take another look at your gfile definition, 03000 doesn't exist in your projects folder.

**Comment by camicollins** [comment]
@alvin-garcia That was it! Thank you.
