### ISSUE TITLE
Reaction rate calculation

### ISSUE THREAD

**Issue by kiselevnightkeo** [D3DEnergetic/FIDASIM#234]
Can you explain how you calculate the reaction rate in the "bt_maxwellian_eb" function?

I thought it was calculating the beam-target reaction rate, but using the formula in the attached picture did not give the desired result.
![image](https://user-images.githubusercontent.com/49403008/110239085-2f280900-7f56-11eb-8dcb-0c0d7a2ed971.png)

Cross section from atomic_tables.h5 (!!)

I  used the following article. 
[fusion_cross_sections_and_reactivities_by_G_Miley_H_Towner_N_Ivich.pdf](https://github.com/D3DEnergetic/FIDASIM/files/6097043/fusion_cross_sections_and_reactivities_by_G_Miley_H_Towner_N_Ivich.pdf)

**Comment by lstagner** [comment]
What result did your calculation give?

**Comment by kiselevnightkeo** [comment]
beam energy eb = 100 keV
Ion temperature Ti = 10 keV

D-D reaction, neutron branch.

Reaction rate by fidasim <sigma*v>= 6.95e-22 m^3/s
Reaction rate by formulae <sigma*v>= 1.39e-23 m^3/s

Could this be related to the 1/2 coefficient from Kronecker’s delta?
![image](https://user-images.githubusercontent.com/49403008/110366272-1bb09700-8057-11eb-856a-999f22ad7c16.png)

But for other lower energy and temperature difference is bigger.

beam energy eb = 10 keV
Ion temperature Ti = 1 keV
Reaction rate by fidasim <sigma*v>= 7.97e-27 m^3/s
Reaction rate by formulae <sigma*v>= 9.4e-26 m^3/s

**Comment by lstagner** [comment]
So a factor of 50. Below is how we calculate

[reaction_rates.pdf](https://github.com/D3DEnergetic/FIDASIM/files/6105112/reaction_rates.pdf)
