### ISSUE TITLE
Bug in Magnetic Field Calculation and COCOS

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#238]
So this is the basic problem. Right now the idl and the python codes make the assumption that the poloidal flux is of the ribbon variety instead of the disk variety (see image below from Flux Coordinates and Magnetic Field Structure: 4.7.1). 

![Flux Coordinates and Magnetic Field Structure: 4.7.1](https://user-images.githubusercontent.com/4305891/116633707-17924e80-a90f-11eb-9017-37680578c60d.png)
The problem is that depending on which interpretation you use the poloidal field can be flipped because `dPsi_disk = -dPsi_ribbon`. 

So far we have recommended using `extract_transp_geqdsk` to get the geqdsk file from a transp run. The poloidal flux outputted is of the ribbon variety where the poloidal flux at the magnetic axis is zero. However if a person uses a geqdsk file from MDSplus or EFIT its using the disk variety. Right now FIDASIM only supports "ribbon" geqdsk. Additionally, some machines have different conventions toroidal coordinate conventions. We need to support all of them.

To that end I suggest we implement the [COCOS](https://www.sciencedirect.com/science/article/pii/S0010465512002962) convention so we can take a geqdsk file, determine the COCOS, and convert it to the convention FIDASIM uses.

We may also want to look into changing how we represent fields in FIDASIM to use the flux function.

@gardner-chris I'm assigning this to you as you are working on the Zeeman splitting and this would probably effect you. 
@shaunhaskey you may of run into this bug.

**Comment by lstagner** [comment]
Looking at the COCOS paper you can see that in the case of a "ribbon" poloidal flux the poloidal field depends on the sign of the current.

<img width="556" alt="Screen Shot 2021-04-30 at 11 01 04 PM" src="https://user-images.githubusercontent.com/4305891/116773071-04af7500-aa08-11eb-8505-077df1753572.png">

**Comment by lstagner** [comment]
Not yet address but its now on my todo list

**Comment by hayashiw** [comment]
@lstagner Since this is an issue that affects geqdsk files but also equilibrium inputs in other formats and from other machines, would the most general solution be to implement COCOS checks and conversions in the `read_equilibrium` subroutine in FIDASIM rather than in preprocessing?

**Comment by lstagner** [comment]
@hayashiw What is the status of this?

**Comment by hayashiw** [comment]
@lstagner I have it implemented on python preFida but it needs to be tested against g-files with different COCOS index. I'm working on the IDL preFida implementation.

**Comment by lstagner** [comment]
If you need gfiles with different cocos check out the files here: https://github.com/ProjectTorreyPines/Equilibrium.jl/tree/master/test

**Comment by hayashiw** [comment]
@lstagner Is this issue closed?

**Comment by lstagner** [comment]
We have cocos support now so it should be fixed.
