### ISSUE TITLE
FIDASIM hangs during `make_diagnostic_grid`

### ISSUE THREAD

**Issue by lamorton** [D3DEnergetic/FIDASIM#247]
This started with [commit](https://github.com/D3DEnergetic/FIDASIM/commit/f5637c04ffcd184bcfcaa0afa94234eb10e1b244#diff-414e4e711e0fd6d33e1e8af3de989057dab11d937d4c3c70df783bc36a16ed87) "xyz_to_uvw bug fix in visualization scripts and utilities (#212)."

I'm using gnu9 compiler suite.  No error messages, just never gets past the `make_diagnostic_grid` routine, even after 1.5hr.  It was instantaneous previously.

**Comment by lamorton** [comment]
I fixed it by switching to the Intel compiler, which is apparently the preferred one on our cluster.

**Comment by lstagner** [comment]
While its good that you resolved the issue we nominally support gfortran so could you send us your input files and we can see if we can get gfortran up and running.
