### ISSUE TITLE
Issue with reading CX rate tables in latest tagged version of FIDASIM(ver3.0.0-dev)

### ISSUE THREAD

**Issue by Antonjvv** [D3DEnergetic/FIDASIM#252]
Hi all,
I want to try running a case with multiple thermal plasma species so switched to the latest version of the master branch (d6879ac6e02265866236f542870b2b99e2454b19). 
However, after compiling and regenerating the atomic tables, my FIDASIM run gets stuck when trying to read the /rates/H_H_cx table:
...
READ_ATOMIC_RATE: Unsupported atomic interaction: /rates/H_H

Looking into this it appears that the read_atomic_rate() function is expecting a H_H_cx table with 4 dimensions, but the table generated has 5 dimensions (n,m,energy,temp,bt_amu). Could it be that the function read_atomic_rate() needs to be updated, or should the CX table in fact have 4 dimensions?
Has anyone else run into this problem?

**Comment by lstagner** [comment]
In order to support multiple species the atomic tables needed to change. So you just need to remake the atomic tables.
