### ISSUE TITLE
Broken test example

### ISSUE THREAD

**Issue by JoseRuedaRueda** [D3DEnergetic/FIDASIM#257]
**Brief report**
1.- The recomended branch in the manual (https://d3denergetic.github.io/FIDASIM/master/page/01_getting_started/01_install.html)  `v3.0.0-dev` does not exist in the repo.
2.- When installing FIDASIM and executing the test run (in the master branch) , an error arise, coming from the dimension of the phi grid

**Error code**
```
INFO: Checking simulation settings...
SUCCESS: Simulation settings are valid
INFO: Checking interpolation grid...
ERROR: "phi" must have at least 3 elements
ERROR: Invalid interpolation grid. Exiting...
```
**Source of the error**
`lib/python/fidasim/preprocessing.py` Lines 302-305. Commit 8bfb2973a8eef603f3319a7e0e95c51e54d9ae4b

**Personal guess**
The format of the phi grid was updated, but the test input file not

**Comment by lstagner** [comment]
Ah good catch

**Comment by lstagner** [comment]
I will say that you should use the release version of FIDASIM (currently v2.0.0) unless you have a specific need for the development version.

**Comment by JoseRuedaRueda** [comment]
Thanks a lot Luke.

After years of delays, I am finally trying to use this version of FIDASIM for my AUG studies instead of the old AUG version.

I do not think I have any special requirements, so I will give a try to the 2.0 and keep Garrett and you posted with the advances
