### ISSUE TITLE
issure in Translating NUBEAM Neutral Beam Geometry

### ISSUE THREAD

**Issue by rink2023** [D3DEnergetic/FIDASIM#264]
I am trying to run the follwing function,
IDL> nbi = nubeam_geometry(nubeam)
but I have no idea where could I get the nubeam structure. The instruction said:
nubeam is a structure/dictionary containing the NUBEAM geometry variables taken from the TRANSP namelist.
How to get this structure in IDL?

**Comment by lstagner** [comment]
The only way to get it in IDL is to hard code it it from the NUBEAM/TRANSP namelist file. For an example checkout out https://github.com/D3DEnergetic/d3d-fidasim/blob/master/src/d3d_beams.pro which uses the same variables as the NUBEAM/TRANSP namelist
