### ISSUE TITLE
issue on Beam grid defination

### ISSUE THREAD

**Issue by rink2023** [D3DEnergetic/FIDASIM#267]
The instruction said that FIDASIM uses Tait-Bryan rotation angles (alpha,beta,gamma) to define a intrinsic rotation matrix, R
, that is used to transform from beam grid coordinates(xyz) to machine coordinates(uvw)
uvw=R⋅xyz+origin
About the defination of alpha,beta,gamma there is an example:
Rotate about your thumb (z-axis) by alpha (ccw = +angle, cw = -angle)
Rotate about your middle finger (y'-axis) by beta
Rotate about your index finger (x"-axis) by gamma

However it still hard for me to calculate the exact angles based on these infomations. Is there any algorithm based on the beam geometry? For example the orientation of one beam is nbi.axis = (-0.991272,0.107698,-0.076034), how do I calculate the Tait-Bryan rotation angles?

**Comment by lstagner** [comment]
There is a useful helper function called `beam_grid` in the `fidasim.utils` module that takes a nbi geometry and radial start position and creates a grid that is aligned with the neutral beam.

https://github.com/D3DEnergetic/FIDASIM/blob/cf37432ed79f3f06f443ca1b53ff732b69d90144/lib/python/fidasim/utils.py#L550-L584
