### ISSUE TITLE
issue when visualize the input and output (see the attached file)

### ISSUE THREAD

**Issue by rink2023** [D3DEnergetic/FIDASIM#269]
![微信截图_20230926145445](https://github.com/D3DEnergetic/FIDASIM/assets/134921531/658fa3d8-9b5f-4471-a423-3755d7bcfaef)
![微信截图_20230926145356](https://github.com/D3DEnergetic/FIDASIM/assets/134921531/19103de1-e53e-4aa0-8653-a655f613398c)

**Comment by lstagner** [comment]
Huh it looks like h5py has [changed its API for version >3.0](https://docs.h5py.org/en/stable/whatsnew/3.0.html#breaking-changes-deprecations). I'll have to change the scripts to use the new API. In the mean while you could either downgrade your h5py library to version 2.10 which is the last compatible API or wait while I make the changes.
