### ISSUE TITLE
reding hdf5 file

### ISSUE THREAD

**Issue by KlaraBogar** [D3DEnergetic/FIDASIM#272]
I am starting to use this version of FIDASIM. I tried to use plot_inputs and also plot_outputs. The values from the original hdf5 file dataset is read by .value (for example: r = eq["/fields/r"].value). However, this approach already does not work for newer versions of h5py and results in the error "'Dataset' object has no attribute 'value'". It is necessary to use for example [...] or [()] (r = eq["/fields/r"][...] or  r = eq["/fields/r"][()]).

**Comment by lstagner** [comment]
The issue has been resolved on the master branch. We are currently in the process of preparing for FIDASIM 3.0 which includes the fixes. Feel free to switch over to the master branch as it is relatively stable but I recommend using v2.0 for any publications.
