### ISSUE TITLE
Bug in the fast-ion distribution mass for mixed isotopes plasmas

### ISSUE THREAD

**Issue by JoseRuedaRueda** [D3DEnergetic/FIDASIM#277]
# Description of the problem

In line 3686, the mass of the fast-ion population is assigned to be the one read from the namelist, as they were beam markers:

https://github.com/D3DEnergetic/FIDASIM/blob/ece16bdc5b31f5210a0c48396677579738688c20/src/fidasim.f90#L3686

This can cause problems if for example we want to study the FIDA or NPA signal using a deuterium fast-ion distribution and an hydrogen beam or viceversa

# Proposed solution 1:
Uncomment the previous line and read the info from the FBM file
https://github.com/D3DEnergetic/FIDASIM/blob/ece16bdc5b31f5210a0c48396677579738688c20/src/fidasim.f90#L3685
## Unwanted side effect
If someone has an old FBM file without this mass information, his program will crash

# Prosed solution 2:
Same as 1 but adding and if in case the variable is not found. If this happen, use beam_mass as up to now
## Unwanted side effect:
Would be possible for users to have Hydrogen FI distributions and D beams, without mass info in the file, and run without core errors

**Comment by lstagner** [comment]
On master it now reads the fast ion mass if it exists in the distribution file.
