### ISSUE TITLE
change reading order in fidasim.f90 

### ISSUE THREAD

**Issue by dnestrov** [D3DEnergetic/FIDASIM#35]
from
    read(66,*) inputs%ab    
    read(66,*) inputs%ai    
to
    read(66,*) inputs%ai    
    read(66,*) inputs%ab

**Comment by lstagner** [comment]
Thanks for opening this issue. 

This has fortunatly already been fixed this [commit](https://github.com/D3DEnergetic/FIDASIM/commit/9e566f5abe7a580f010de9bcc3cf90f0a5e24786).  

You should be aware that there is a new version of FIDASIM [v0.3.0](https://github.com/D3DEnergetic/FIDASIM/releases/tag/v0.3.0) that was released this past October. It is a significant improvement over the last version. It includes various bugfixes and other improvements for user experience.

You may have to make some changes to your workflow and device routines to get the new version to work. The largest changes is the new NPA weight function routines(chord structure has changed) and the new input file format(apart from some variable name differences the old format still works). I would suggest reading the README.md.

If you have any problems getting the new version of FIDASIM to run just post to this issue again.
