### ISSUE TITLE
Tables in netCDF format

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#44]
Binary files are a pain to deal with and everything else in FIDASIM uses netCDF

**Comment by geigerb** [comment]
... didn't you plan to use h5 format in the future?

**Comment by lstagner** [comment]
You're right I even have an issue open (Issue #15 ). HDF5 files are better supported by more languages. If we were to switch over it would be better to do it sooner rather then later since we are already going to be breaking backwards compatibility with the new interpolation routines. So long as I still include a way for people to read the old files it should be fine.

**Comment by lstagner** [comment]
Went with HDF5. Fixed in #64
