### ISSUE TITLE
Need to launch beam neutral at ion source location, not beam aperture location

### ISSUE THREAD

**Issue by deyongl** [D3DEnergetic/FIDASIM#62]
The current FIDAsim version launches beam neutrals at beam aperture location, not the ion source location. For a perfectly collimated neutral beam, this is not a problem. However, for any beam with divergence, it induces inaccuracy in beam neutral density profile and magnitude. One example is shown in Fig. 1 and Fig. 2.  The beam and halo neutral densities spread much wider and the peak magnitudes are much smaller when launching beam neutrals at ion source location.  They will not only change the FIDA light intensity and also modify the FIDA spatial profile. For a NSTX case, it shifts the peak of simulated FIDA spatial profile inward by 5cm, which make the simulation results closer to experimental measurements.  

![centerline](https://cloud.githubusercontent.com/assets/12468380/8674542/9bf3edb0-2a0c-11e5-983c-a294ed4d31a7.png)
Fig.1  Comparison of beam and halo neutral densities along the NB centerline when launching beam neutrals at beam aperture location (solid lines) and ion source location (dashed lines)

![perpendicular](https://cloud.githubusercontent.com/assets/12468380/8674543/9bf4eb66-2a0c-11e5-8f95-95eb39910440.png)
Fig.2  Comparison of beam and halo neutral densities perpendicular to the NB centerline when launching beam neutrals at beam aperture location (solid lines) and ion source location (dashed lines)

**Comment by bgrierson21** [comment]
These differences look enormous.  The IDL FIDASIM launched particles from the ion source, not aperture.  NUBEAM launches form the ion source, not aperture.  In the past, we have shown good agreement with NUBEAM, so how can this be so very different?

**Comment by deyongl** [comment]
To my understanding, the large discrepancy is mainly because of the existence of beam divergence. Since the ion source location is almost twice away from the machine center compared with beam aperture location, the beam footprint is expected to be  spread in space when beam neutrals are launched at ion source location. Of course, beam focus will try to limit the growth of the beam footprint.

When I worked on the 3D halo benchmarking project with Fortran FIDAsim, I launched beam neutrals at ion source location and beam neutral density profile and magnitude are consistent with TRANSP/NUBEAM calculations. When I worked on my PhD these with IDL version FIDAsim (which also launches beam neutrals at ion source location), they also get agreement with TRANSP/NUBEAM modeling. It is the Fortran version (starting from last summer to now) that launch beam neutrals at beam aperture location. I personally don't know whether is any case that FIDAsim get good agreement with NUBEAM when beam neutrals are launched at aperture location.

**Comment by lstagner** [comment]
@bgrierson21 Technically FIDASIM launches particles from wherever xyz_src is defined to be. For the D3D case I believe xyz_src is defined to be at the ion source so any D3D benchmarks would be fine.  Originally we did not think it where xyz_src was defined so long as it was on the beam sightline. This is apparently not the case.

Relatively soon, I am going to integrate the NBI apertures into FIDASIM. This should make it explicit that xyz_src has to be at the ion source.

**Comment by lstagner** [comment]
Fixed in #64
