### ISSUE TITLE
Intensity issue

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#85]
@lstagner @bgrierson21 I have been trying to chase down the intensity difference between main ion CER simulations using the old and new FIDASIMs. It seems as though the issue might be related to the beam ion density. I have plotted the n=3 neutrals from old FIDASIM (right plot) and new FIDASIM (left plot). The top row shows the neutrals from fdens, hdens and tdens. The bottom row is DCX+halo, DCX, and Halo only. As far as I can tell the pinj and einj were the same for both simulations. We need to scale the fdens by a factor of about 2.2 to get to the old fdens. The same factor appears to be required for DCX+halo (what gives the main ion CER intensity).

![screenshot_346](https://cloud.githubusercontent.com/assets/3589208/14619174/074c3b46-056b-11e6-8d13-f68b209e77b0.png)

I'll keep checking to make sure the inputs are the same, but unless I have made a mistake, it seems that there might be an issue with scaling of the beam deposition...

**Comment by bgrierson21** [comment]
First check the ground state beam neutral density (in the SOL) to make sure that the beam power and voltage are putting in the correct stream of neutral particles for both codes.  Then compare the levels (n=1,2,3) and see where they begin to disagree.

**Comment by lstagner** [comment]
Curious, I have benchmarking against a test case since I started developing. 

Below is a comparison of the total neutral density (integrated over y, z, and n-level) the old and new version
![test_1b](https://cloud.githubusercontent.com/assets/4305891/14619670/58d05c2a-056d-11e6-83a9-79d9d68c9eda.png)

The drop in the halo is expected due to the new lower energy bounds and resolution. 

I haven't been checking the individual energy levels so I could be that while the sum over the energy levels is the same the individual levels differ.

**Comment by shaunhaskey** [comment]
Hmmm.... well hopefully I'm doing something wrong. Here is the n=1 comparison and the differences are still there, so there must be something messed up with the input power.... Will keep digging.

![screenshot_347](https://cloud.githubusercontent.com/assets/3589208/14619814/2bead50e-056e-11e6-93c7-ae0b683e2590.png)

**Comment by shaunhaskey** [comment]
The input beam information seems to be the same, see the values in geometry.h5, and input.cdf below:

![screenshot_348](https://cloud.githubusercontent.com/assets/3589208/14620017/5e1c4372-056f-11e6-9bd9-0835815797fe.png)

**Comment by lstagner** [comment]
I just did the comparision of the different levels for the test cases and there is no difference

Below is the n=3 case
![test_1b_n3](https://cloud.githubusercontent.com/assets/4305891/14620107/d7cf7f2c-056f-11e6-91d2-c77ad9f59193.png)

The benchmarks are comparing against the release-0.3 branch. Is your old-version of FIDASIM the same as mine?

**Comment by shaunhaskey** [comment]
You make a convincing argument..... See below for what I was using (note the uncommitted changes were the default number of threads) 

![screenshot_349](https://cloud.githubusercontent.com/assets/3589208/14620429/78bc2420-0571-11e6-9248-4927c395494b.png)

will keep looking

**Comment by lstagner** [comment]
I will rerun the test cases on the release branch just in case

**Comment by shaunhaskey** [comment]
@lstagner Any chance you could plot the maximum value in each y, z plane as a function of x for n=1 and compare those? I found that there was decent agreement for the total neutrals in each y, z plane for me (differences due to slightly different geometery), however, there is a large difference in the maximum value in each plane. Apparently this is due to very different looking plots in the x-z plane:

![screenshot_350](https://cloud.githubusercontent.com/assets/3589208/14622151/d0b9a750-057c-11e6-9088-25f9d20a633e.png)

The plot on the left (new FIDASIM) does not look very good.... Maybe I need to increase my RZ grid

**Comment by lstagner** [comment]
The max value of the new version is consistently smaller but not small enough to cause the difference you see.

![test_1b_max](https://cloud.githubusercontent.com/assets/4305891/14622722/ecd6a330-0580-11e6-8fdc-b5148a64943f.png)

**Comment by shaunhaskey** [comment]
Thanks for checking that, guess I have to keep hunting.... By the way, the strange shape of the plots in the x-z plane were not fixed by increasing the number of points in the RZ grid that the profiles are interpolated onto.

**Comment by shaunhaskey** [comment]
Hi Luke, 

Has anything strange changed in the way the beam is specified? I.e the divergence and focal lengths of the beam?  This is essentially the code that I am using from d3d_beams.pro Can you see anything strange here?

```
	uvw_src=[[double(us_NB)],[double(vs_NB)],[replicate(0.0d,nsources)]]
        ;; Location of the crossover in machine coordinates
	uvw_pos=[[double(u_co)],[double(v_co)],[replicate(0.0d,nsources)]]
        axis = uvw_pos - uvw_src

	bmwidra=6d0     ; ion source half width in cm
	bmwidza=24d0    ; ion source half height in cm
        focy=replicate(999999.9d0,nsources) ; so f90 can read input 
	focz=replicate(1000d0,nsources)      ; vertical focal length is 10 m
	divy=replicate(8.73d-3,3,nsources)    ; horizontal divergence in radians
	divz=replicate(2.27d-2,3,nsources)
    ;;SAVE IN NBI STRUCTURE
    cur_axis = reform(axis[inputs.isource,*])
    axis = cur_axis/sqrt(total(cur_axis^2.0))
	nbi={circular:0,einj:einj,pinj:pinj,full:ffracs,half:hfracs,third:tfracs,$
             uvw_src:reform(uvw_src[inputs.isource,*]),uvw_pos:reform(uvw_pos[inputs.isource,*]),bmwidra:bmwidra,bmwidza:bmwidza,$
             divy:divy[*,inputs.isource],divz:divz[*,inputs.isource],focy:focy[inputs.isource],focz:focz[inputs.isource],$
             src:reform(uvw_src[inputs.isource,*]),axis:axis,widy:bmwidra,widz:bmwidza}
```

I'm pretty sure the problem is because the beam is too tall in the simulation grid....

**Comment by lstagner** [comment]
No nothing has changed in regards to the divergences/focus. I actually use the same beam config in the test case, although not the same orientation.

**Comment by lstagner** [comment]
I just looked at your def_geometry.h5 file and it says the the following.
```idl
IDL> print,a.nbi.focy    
{ Horizonal focal length of the beam cm       999999.90}
IDL> print,a.nbi.focz
{ Vertical focal length of the beam cm       999999.90}
```

That is not right

**Comment by shaunhaskey** [comment]
@lstagner Where are you looking? I just started a run where I set the focz=focy and divz=divy to see what happens. Then I was going to make the width and height of the source the same just to make sure the simulation gives decent symmetry in the x-y and x-z planes

**Comment by lstagner** [comment]
```
/venus-scratch/haskeysr/OMFIT/runs/projectID__ab42d7ab84__2016-04-13_19_12_29/FIDASIM/p0
```

**Comment by shaunhaskey** [comment]
yep that is the the case where I changed things to see what happens.

I think nbi.focy should be 999999.90 though - that is what d3d_beams.pro sets it to.

**Comment by lstagner** [comment]
yeah thats what focy should be.

Have you double checked the profiles?

**Comment by lstagner** [comment]
You could calculate the birth profile (It wont cost you any noticeable time). That way you could back track the particles to the source.

**Comment by lstagner** [comment]
Something may be going wrong with the coordinate transformations. Could you try a non-rotated grid?

**Comment by lstagner** [comment]
Well damn

In the test case I moved the source back 1.5 m and this is what you get for the vertical dispersion
![test_1a_new_src](https://cloud.githubusercontent.com/assets/4305891/14698834/6d82b3ee-0747-11e6-8e06-0d41aad338e4.png)

It wasn't extremely noticeable when the source was closer. 

Problem is I have no idea what I did wrong. 

The relevant section of code is the [mc_nbi routine](https://github.com/D3DEnergetic/FIDASIM/blob/master/src/fidasim.f90#L5445)

**Comment by lstagner** [comment]
It was a minus sign error. Fix has been pushed to master

The problem was with this piece of code
```
    xyz_ray(1) = 1.d0
    xyz_ray(2)=(xyz_src(2)/nbi%focy + tan(nbi%divy(efrac)*randomn(1)))
    xyz_ray(3)=(xyz_src(3)/nbi%focz + tan(nbi%divz(efrac)*randomn(2)))
```
It should of been 
```
    xyz_ray(1) = 1.d0
    xyz_ray(2)=(-xyz_src(2)/nbi%focy + tan(nbi%divy(efrac)*randomn(1)))
    xyz_ray(3)=(-xyz_src(3)/nbi%focz + tan(nbi%divz(efrac)*randomn(2)))
```

The reason I didn't catch it is because the old version didn't have the minus sign either, rather it was folded into the beam rotation.

Here is the same plot as above but corrected.
![test_1a_new_src_corrected](https://cloud.githubusercontent.com/assets/4305891/14705782/149888a2-0770-11e6-9016-fa281e4b6259.png)

**Comment by shaunhaskey** [comment]
Thanks for finding that! Now the main ion CER chord intensity agrees well between the old and new version of FIDASIM (left is old, right is new, good to within a few percent which could easily be accounted for by things like increasing the number of particles and depth of the atomic tables). 

![screenshot_356](https://cloud.githubusercontent.com/assets/3589208/14719543/a7392838-07b1-11e6-8680-a21a8624b4ec.png)

I hope you are including the new test with the source farther away for any future testing!

**Comment by lstagner** [comment]
I think I will.

Does the new version agree with the data better? It look like it may in the trot panel but the markers are not consistent with the legend

**Comment by bgrierson21** [comment]
There is no experimental spectroscopic data on that plot.  Thanks Shaun and Luke for figuring this out!  Just in time for intensive analysis for upcoming meetings.

**Comment by shaunhaskey** [comment]
Unfortunately I can't use the data as a good test because we don't expect FIDASIM and the measured 'apparent' data to agree (unless the carbon and deuterium profiles are the same, because the carbon profiles are usually the inputs to FIDASIM)... The measured 'apparent' data needs corrections due to things like smearing (mainly due to halo) and cross-section effects (from DCX). We need FIDASIM to forward model what the apparent signal should be.... So given the actual profiles, FIDASIM will generate the apparent values each chord will see, then you can go back and forth and try to decide what the actual profiles should be based on the apparent measurements....

Maybe the intensity would be a better check, but again, that comes along with the assumptions from quasi neutrality (i.e that carbon is the only impurity and things like fast ions aren't a significant contribution to ne). I'm actually working on trying to figure out a fast ion density using FIDASIM based on ne, n_carbon, and the intensity of the D-alpha thermal intensity for one of Cami's shots (Mike has been bugging me about doing this). Hmmm... I guess a low impurity ECRH  only (no fast D-alpha...) shot would be the best comparison for the intensity because n_e~=n_D.

**Comment by lstagner** [comment]
Unless there are any more major discrepancies I am closing this issue.
