### ISSUE TITLE
Issue with long path and filename

### ISSUE THREAD

**Issue by shaunhaskey** [D3DEnergetic/FIDASIM#91]
For some reason FIDASIM output def_spectra.h (instead of def_spectra.h5) on one of my runs. Here is what is said in the log file:

   Spectra written to: /p/omfit/tmp/shaskey/OMFIT/runs/projectID__83d28a6af7__2016-05-05_09_46_20/FIDASIM_V1.0_1_noCorrection/p1//def_spe\
ctra.h

I assume this is due to the very long filename....? I will change the def_inputs.dat, so the results directory isn't so crazy, but it might be worth updating to allow a longer filename.

This is using: Version: v0.3.2-29-ge20bcf7

**Comment by lstagner** [comment]
Ahh the joys of statically compiled languages. I'll fix it and also make fidasim fail if peoples strings are too long :smiling_imp:

**Comment by lstagner** [comment]
Fixed. I bumped up the character limit and added a compliance test.
