### ISSUE TITLE
RFC: Citation Policy

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#93]
I am writing the FIDASIM manual right now and I am including a "How to Cite FIDASIM" section. This is basic outline of what I think would be a good citation policy
## 1. Always cite the source code

From the standpoint of reproducible science the specific source code version should always be cited. Whenever a new version of FIDASIM is released we can assign a citable [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) using this [guide](https://guides.github.com/activities/citable-code/). I have done this for [my own code](https://github.com/lstagner/PPCF-58-4-2016) in the past.
## 2. Cite the paper that describes the primary FIDASIM capability that you are using

FIDASIM has grown into more than just a code for simulating FIDA light. A user may only use FIDASIM for a specific use. For instance some people may only be using FIDASIM for the neutral beam modelling, or the weight functions. Therefore, in addition to the source code citation, a user should cite the relevant physics papers. For instance, If someone is using FIDASIM to simulate Neutral Particle Analyzers they should only have to cite the paper that describes the NPA calculation (which we still need to write). 

This way of citing has the benefit of making sure everyone who contributes to FIDASIM will get credit. It also prevents newer citations supplanting older ones. Additionally, it should make writing new papers simpler since they would only have to focus on the new features without having to explain how FIDASIM works.

**Comment by shaunhaskey** [comment]
@lstagner How is this coming along? I would like to include this citation in my HTPD paper

**Comment by lstagner** [comment]
I am waiting for the resolution of https://github.com/D3DEnergetic/nstx-fidasim/issues/4 . I dont want to tag a release if one of the new features is possibly broken. It looks like it will be resolved soon so I am hoping to tag it by Monday.

**Comment by lstagner** [comment]
I managed to fix the issue that was blocking the release. All I have to do now is set up Travis CI to automatically build and deploy the documentation website (Issue #75 ).

I have run into an issue I think warrants discussion. The DOI issued by Zenodo is valid, however, since it doesn't point to a peer-reviewed paper it doesn't get incorporated into the common metrics used by academic institutions and funding agencies to determine if I am a good researcher. If I encourage using the DOI, FIDASIM will get cited but it wouldn't be a *real* citation. 

There is a new peer-reviewed journal that is specifically for research software that addresses this issue. It called the [The Journal of Open Source Software](http://joss.theoj.org/) and I know that [people behind it](http://joss.theoj.org/about#editorial_board) are well-respected in their communities. I think we should consider submitting a software paper with them.

I should make it clear that publishing in this journal would not replace publishing in a physics journal. The citation would be for the software and related documentation only. The physics behind each new feature would be a separate physics publication.

@arfon I know you're probably busy but I would welcome any insights you may have

**Comment by arfon** [comment]
> I should make it clear that publishing in this journal would not replace publishing in a physics journal. The citation would be for the software and related documentation only. The physics behind each new feature would be a separate physics publication.

Yep, that's exactly the purpose here. Currently the only way to be assured of career-credit for software is to write a software paper. [JOSS](http://joss.theoj.org) is designed to make this process as easy as possible by only allowing short (abstract-length) papers.

**Comment by shaunhaskey** [comment]
You aren't tempted to put in a 3 page HTPD paper?

**Comment by lstagner** [comment]
I did consider writing up a HTPD paper but it was decided that it would be best not to since we want to write a longer paper(>3 pages) on the new physics features that Ben Geiger(3D halo) and I (NPA) implemented. If we want that paper we cant also have a HTPD paper. [Reviewers don't like that](https://www.youtube.com/watch?v=RfprRZQxWps).

So if I can't discuss the new physics features (which really aren't new since they were in the old version of FIDASIM as well) what would I put into the HTPD paper?

**Comment by lstagner** [comment]
I got the OK from Bill. @geigerb would you be OK with this. It would't supersede the physics paper you are writing.
