### ISSUE TITLE
Logo for FIDASIM and D3DEnergetic Group?

### ISSUE THREAD

**Issue by lstagner** [D3DEnergetic/FIDASIM#94]
This is mainly just for fun. Does anyone have any ideas?

**Comment by lstagner** [comment]
If no body suggests anything I'm just use this picture of a neutral beam
![neutral-beam](https://cloud.githubusercontent.com/assets/4305891/15277288/8cffc07e-1ab4-11e6-8de3-462c53361138.png)

**Comment by bgrierson21** [comment]
That's pretty good.

**Comment by lstagner** [comment]
How about this.

![fidasim-logo](https://cloud.githubusercontent.com/assets/4305891/15296954/9a483868-1b4c-11e6-9904-9344ea6f7654.png)

I found a pretty nice tool for making logos.
https://logomakr.com/

**Comment by bgrierson21** [comment]
That looks like we're selling washing machines.  We need something that conveys the charge-exchange process with a fast-ion orbit and beam neutral.

**Comment by lstagner** [comment]
This one seems more collisionally. 
![fidasim-logo2](https://cloud.githubusercontent.com/assets/4305891/15297376/a5077014-1b4e-11e6-8880-c574c6b49e64.png)

**Comment by lstagner** [comment]
![fidasim-logo4](https://cloud.githubusercontent.com/assets/4305891/15297658/27cd06a2-1b50-11e6-9ac6-f1a04e5a51a7.png)

**Comment by lstagner** [comment]
OK I think this one is it.
![fidasim-logo-final](https://cloud.githubusercontent.com/assets/4305891/15304426/1b9b1fdc-1b72-11e6-9444-291f725edbb9.png)

**Comment by shaunhaskey** [comment]
Almost as good as the neutral beam

**Comment by Nathan-Bolte** [comment]
The last one is looking much better.

**Comment by lstagner** [comment]
OK I went with the last one and updated the [website](http://d3denergetic.github.io/FIDASIM/).
